name: Notify Telegram on Update

on:
  push:
    branches:
      - main 

jobs:
  telegram_notification:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Get Commit Message
      id: get_commit_message
      run: echo "::set-output name=message::$(git log -1 --pretty=format:%s)"
      # This command fetches the last commit message

    - name: Send Notification to Telegram
      if: "contains(steps.get_commit_message.outputs.message, '[DEBUG]') == false"
      # This condition checks if the commit message does not contain '[DEBUG]'
      uses: appleboy/telegram-action@master
      with:
        to: ${{secrets.TELEGRAM_CHAT_ID }}
        token: ${{ secrets.TELEGRAM_TOKEN }}
        message: "${{steps.get_commit_message.outputs.message}}. Check out the latest content at https://abdirayimov.me/"
